input_img_dir: /data/nofar/0621/
lib_paths:
  yoloe2e: /home/lorenzo/Code/toolsbox/libs/libyoloe2e-c.so
  yolov8obb: /home/lorenzo/Code/toolsbox/libs/libyolov8obb-c.so
models:
  - model_path: /data/lorenzo/nofar/Detection/model_version/model8e2e_b32m_20250619_hbb_cls10_action_v0.5.8_b16_fp16.bin
    class_names: ["fire", "smoke", "person", "nomask", "smoking", "nowf", "fall", "sleep", "tx", "wsf"]
    class_filter: ["person", "nomask", "smoking", "nowf", "fall", "sleep", "tx", "wsf"]
    conf_threshold: 0.25
    nms_threshold: 0.45
  - model_path: /data/lorenzo/nofar/Detection/model_version/model8e2e_b32m_20250620_fire_smoke_v0.1_b16_fp16.bin
    class_names: ["fire", "smoke"]
    class_filter: ["fire", "smoke"]
    conf_threshold: 0.25
    nms_threshold: 0.45